url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
user=system
password=123456
database=ORCLPDB1
schema.list=C##TEST_REDO
miner.mode=file
#tableList=redo_record
start.scn=4571351
origin.path=/opt/oracle
target.path=D:\\AI-project\\code2\\test
redo.filename=D:\\AI-project\\code2\\log\\redo03.log
